#[derive(Debug, Clone)]
pub enum Message {
    MenuUuidPressed,
    MenuPwdPressed,
    MenuTimePressed,
    MenuEncoderPressed,
    MenuBasePressed,
    MenuRegexPressed,
    MenuQrcodePressed,
    MenuColorPressed,
    MenuCrontabPressed,
    BtnUuidPressed,
    BtnPwdPressed,
    BtnTimePressed,
    UuidCountInputChanged(String),
    UuidCheckUpperToggled(bool),
    UuidCheckSplitToggled(bool),
    UuidCheckBraceToggled(bool),
    PwdCheckUpperToggled(bool),
    PwdCheckLowerToggled(bool),
    PwdCheckDigitToggled(bool),
    PwdCheckSpecialToggled(bool),
    PwdSliderChanged(u8),
    PwdLenInputChanged(String),
    PwdNumInputChanged(String),
}
